Fix issue with version check

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -254,7 +254,9 @@ if [ ! -f "$CACHED_TAR" ]; then
   configure_carbon_relay
 
   topic 'Checking StatSite CLI'
+  set +e # Temp disable exit on non success status as statsite version check has a return code of 1
   version_output=$(statsite -v 2>&1)
+  set -e
   if [[ ! $version_output  =~ "statsite version "[0-9]+\.[0-9]+\.[0-9]+ ]]; then
     topic "StatStat version output didn't match expected format"
     echo "Expected pattern: /statsite version [0-9]+\.[0-9]+\.[0-9]+/" | indent
@@ -268,7 +270,7 @@ if [ ! -f "$CACHED_TAR" ]; then
   version_output=$(carbon-relay-ng version 2>&1)
   if [[ ! $version_output  =~ "carbon-relay-ng "[0-9]+\.[0-9]+\.[0-9]+ ]]; then
     topic "StatStat version output didn't match expcted format"
-    echo "expected regex format: /carbon-relay-ng version [0-9]+\.[0-9]+\.[0-9]+/" | indent
+    echo "expected regex format: /carbon-relay-ng [0-9]+\.[0-9]+\.[0-9]+/" | indent
     echo "Output" | indent
     echo $version_output
     exit 1
